const CREATED_PERSON = 'CREATED_PERSON';
const LOADED_PERSONS = 'LOADED_PERSONS';
const UPDATED_PERSON = 'UPDATED_PERSON';
const DELETED_PERSON = 'DELETED_PERSON';
const ERROR_OCCURED = 'ERROR_OCCURED';

export {
  CREATED_PERSON,
  LOADED_PERSONS,
  UPDATED_PERSON,
  DELETED_PERSON,
  ERROR_OCCURED,
};
